#!/usr/bin/env bash

port=${1:-${PORT:-8080}}

echo "Starting: serveo ${port}"
echo "[now] $(which screen)"
ssh-keygen -t rsa -N "" -f ./id_rsa
eval "screen -S serveo -dm ./serveo -private_key_path ./id_rsa -port=8888 -http_port=${port} -https_port=4433 -domain=tunnelssh.herokuapp.com"
main_pid=$!

 while true; do sleep 10; done
